### ISSUE TITLE
Chromedriver complains chrome has crashed

### ISSUE THREAD

**Issue by hybras** [PussTheCat-org/docker-proxitok-quay#4]
I'm using ur docker compose file unmodified

```
Fatal error: Uncaught Facebook\WebDriver\Exception\UnknownErrorException: unknown error: Chrome failed to start: crashed. (chrome not reachable) (The process started from chrome location /usr/lib/chromium/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) in /var/www/html/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:139 
Stack trace: 
#0 /var/www/html/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php(372): Facebook\WebDriver\Exception\WebDriverException::throwException('unknown error', 'unknown error: ...', Array) 
#1 /var/www/html/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php(131): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand)) 
#2 /var/www/html/vendor/pablouser1/tikscraper/src/Helpers/Signer.php(65): Facebook\WebDriver\Remote\RemoteWebDriver::create('http://proxitok...', Object(Facebook\WebDriver\Remote\DesiredCapabilities)) 
#3 /var/www/html/vendor/pablouser1/tikscraper/src/Helpers/Signer.php(35): TikScraper\Helpers\Signer->setupSelenium('http://proxitok...') 
#4 /var/www/html/vendor/pablouser1/tikscraper/src/Sender.php(37): TikScraper\Helpers\Signer->__construct(Array) 
#5 /var/www/html/vendor/pablouser1/tikscraper/src/Api.php(18): TikScraper\Sender->__construct(Array) 
#6 /var/www/html/app/Helpers/Wrappers.php(88): TikScraper\Api->__construct(Array, Object(App\Cache\RedisCache)) 
#7 /var/www/html/app/Controllers/UserController.php(14): App\Helpers\Wrappers::api() 
#8 [internal function]: App\Controllers\UserController::get('blumineck') 
#9 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(476): forward_static_call_array(Array, Array) 
#10 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(440): Bramus\Router\Router->invoke('UserController@...', Array) 
#11 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(287): Bramus\Router\Router->handle(Array, true) 
#12 /var/www/html/index.php(14): Bramus\Router\Router->run() 
#13 {main} thrown in /var/www/html/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php on line 139
```

**Comment by TheFrenchGhosty** [comment]
Chromedriver isn't needed anymore, so this shouldn't be a problem.

**Comment by hybras** [comment]
new compose file works fine

**Comment by TheFrenchGhosty** [comment]
@hybras Perfect :)
